#!/bin/bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Netresearch DTT GmbH

## Description: Run PHPStan static analysis
## Usage: phpstan
## Example: "ddev phpstan"

echo "Running PHPStan analysis (level 10)..."
.Build/bin/phpstan analyse -c Build/phpstan/phpstan.neon
